### ISSUE TITLE
Suggestion: support html-like language settings in vue template

### ISSUE THREAD

**Issue by litingyes** [codemirror/lang-vue#1]
<img width="869" alt="Screenshot 2023-06-13 at 10 14 33" src="https://github.com/codemirror/lang-vue/assets/69500429/af258492-c2f7-4040-81cb-e4d570fdcfdb">

**Comment by marijnh** [comment]
Does attached patch look like it would address your issue?

**Comment by litingyes** [comment]
Thank you very much 🙏, the **autoCloseTags** in vue template is working!

**Comment by marijnh** [comment]
Tagged a 0.1.2
