### ISSUE TITLE
Support for SASS, SCSS syntax markup in lang-vue

### ISSUE THREAD

**Issue by jongwoo328** [codemirror/lang-vue#2]
Thanks to codemirror for the lang-vue support.
[vue does support preprocessors](https://vuejs.org/api/sfc-spec.html#pre-processors) for sass,scss for the <style> tag in SFC (although it requires an additional dependency to build).
Currently, the lang-vue package does not display syntax for the style tag when the attribute is set to lang="sass" or lang="scss".
It would be cool to support syntax marking for sass and scss.
Is this by design? If not, could it be added?

**Comment by marijnh** [comment]
If I understand you correctly, I think it should be possible to pass a `base` option to `vue` holding something like `html({nestedLanguages: ...})` to configure this.
